// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2p9VhVhxAWhB5Nusx9QUQ2
// Component: p0K-EyPzT18N

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 2p9VhVhxAWhB5Nusx9QUQ2/projectcss
import sty from "./PlasmicAboutUsComponent.module.css"; // plasmic-import: p0K-EyPzT18N/css

createPlasmicElementProxy;

export type PlasmicAboutUsComponent__VariantMembers = {};
export type PlasmicAboutUsComponent__VariantsArgs = {};
type VariantPropType = keyof PlasmicAboutUsComponent__VariantsArgs;
export const PlasmicAboutUsComponent__VariantProps =
  new Array<VariantPropType>();

export type PlasmicAboutUsComponent__ArgsType = {};
type ArgPropType = keyof PlasmicAboutUsComponent__ArgsType;
export const PlasmicAboutUsComponent__ArgProps = new Array<ArgPropType>();

export type PlasmicAboutUsComponent__OverridesType = {
  root?: Flex__<"div">;
  columns?: Flex__<"div">;
  freeBox?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
};

export interface DefaultAboutUsComponentProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAboutUsComponent__RenderFunc(props: {
  variants: PlasmicAboutUsComponent__VariantsArgs;
  args: PlasmicAboutUsComponent__ArgsType;
  overrides: PlasmicAboutUsComponent__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $translator = usePlasmicTranslator?.();

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"columns"}
        data-plasmic-override={overrides.columns}
        className={classNames(projectcss.all, sty.columns)}
      >
        <div className={classNames(projectcss.all, sty.column__lAsWt)}>
          <div
            data-plasmic-name={"freeBox"}
            data-plasmic-override={overrides.freeBox}
            className={classNames(projectcss.all, sty.freeBox)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___1UIv
              )}
            >
              <Trans__>{"The Halcyon Studio Story"}</Trans__>
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__lm3Sm
              )}
            >
              <Trans__>
                {
                  "\r\nThe inspiration behind creating Halcyon Studio stems from my belief that all forms of movement can be profoundly healing, both physically and mentally. My goal is to offer a variety of classes to help you discover what makes you feel good and supports your well-being. My own healing journey has been transformative, and just a year ago, I never imagined I\u2019d be creating this space. Life can change in an instant, turning everything upside down, but it's crucial to get back up and continue striving for oneself. After facing several personal challenges, I found solace in movement, and support in my husband, family, and friends. Halcyon Studio came to life with these concepts as its core.\n\n\r\n\r\nWhen choosing the name, I wanted it to reflect something significant and aligned with the studio's purpose. That\u2019s why I chose \u201cHalcyon,\u201d a word that embodies the peace and tranquility I hope to bring to your life. Our focus is on movement and wellness, and we\u2019re continually looking to expand what we offer to support you on your journey. My primary intention is for you to walk through our doors, leave your worries behind, and dedicate time to caring for yourself\u2014moving in the way that feels right for you."
                }
              </Trans__>
            </div>
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.column__cRYd)}>
          <PlasmicImg__
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames(sty.img)}
            displayHeight={"100%"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"100%"}
            loading={"lazy"}
            src={{
              src: "/plasmic/copy_of_halcyon_studios/images/image12.png",
              fullWidth: 1665,
              fullHeight: 1733,
              aspectRatio: undefined
            }}
          />
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "columns", "freeBox", "img"],
  columns: ["columns", "freeBox", "img"],
  freeBox: ["freeBox"],
  img: ["img"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  columns: "div";
  freeBox: "div";
  img: typeof PlasmicImg__;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAboutUsComponent__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAboutUsComponent__VariantsArgs;
    args?: PlasmicAboutUsComponent__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicAboutUsComponent__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicAboutUsComponent__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAboutUsComponent__ArgProps,
          internalVariantPropNames: PlasmicAboutUsComponent__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAboutUsComponent__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAboutUsComponent";
  } else {
    func.displayName = `PlasmicAboutUsComponent.${nodeName}`;
  }
  return func;
}

export const PlasmicAboutUsComponent = Object.assign(
  // Top-level PlasmicAboutUsComponent renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    columns: makeNodeComponent("columns"),
    freeBox: makeNodeComponent("freeBox"),
    img: makeNodeComponent("img"),

    // Metadata about props expected for PlasmicAboutUsComponent
    internalVariantProps: PlasmicAboutUsComponent__VariantProps,
    internalArgProps: PlasmicAboutUsComponent__ArgProps
  }
);

export default PlasmicAboutUsComponent;
/* prettier-ignore-end */
