// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2p9VhVhxAWhB5Nusx9QUQ2
// Component: B45lS1hhx1Vs

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { Embed } from "@plasmicpkgs/plasmic-basic-components";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 2p9VhVhxAWhB5Nusx9QUQ2/projectcss
import sty from "./PlasmicMarianaScheduleCode.module.css"; // plasmic-import: B45lS1hhx1Vs/css

createPlasmicElementProxy;

export type PlasmicMarianaScheduleCode__VariantMembers = {};
export type PlasmicMarianaScheduleCode__VariantsArgs = {};
type VariantPropType = keyof PlasmicMarianaScheduleCode__VariantsArgs;
export const PlasmicMarianaScheduleCode__VariantProps =
  new Array<VariantPropType>();

export type PlasmicMarianaScheduleCode__ArgsType = {};
type ArgPropType = keyof PlasmicMarianaScheduleCode__ArgsType;
export const PlasmicMarianaScheduleCode__ArgProps = new Array<ArgPropType>();

export type PlasmicMarianaScheduleCode__OverridesType = {
  marianaScheduleCode?: Flex__<typeof Embed>;
};

export interface DefaultMarianaScheduleCodeProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicMarianaScheduleCode__RenderFunc(props: {
  variants: PlasmicMarianaScheduleCode__VariantsArgs;
  args: PlasmicMarianaScheduleCode__ArgsType;
  overrides: PlasmicMarianaScheduleCode__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $translator = usePlasmicTranslator?.();

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <Embed
      data-plasmic-name={"marianaScheduleCode"}
      data-plasmic-override={overrides.marianaScheduleCode}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "__wab_instance",
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.marianaScheduleCode
      )}
      code={'<div data-mariana-integrations="/schedule/daily"></div>'}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  marianaScheduleCode: ["marianaScheduleCode"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  marianaScheduleCode: typeof Embed;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMarianaScheduleCode__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMarianaScheduleCode__VariantsArgs;
    args?: PlasmicMarianaScheduleCode__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicMarianaScheduleCode__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMarianaScheduleCode__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMarianaScheduleCode__ArgProps,
          internalVariantPropNames: PlasmicMarianaScheduleCode__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMarianaScheduleCode__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "marianaScheduleCode") {
    func.displayName = "PlasmicMarianaScheduleCode";
  } else {
    func.displayName = `PlasmicMarianaScheduleCode.${nodeName}`;
  }
  return func;
}

export const PlasmicMarianaScheduleCode = Object.assign(
  // Top-level PlasmicMarianaScheduleCode renders the root element
  makeNodeComponent("marianaScheduleCode"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicMarianaScheduleCode
    internalVariantProps: PlasmicMarianaScheduleCode__VariantProps,
    internalArgProps: PlasmicMarianaScheduleCode__ArgProps
  }
);

export default PlasmicMarianaScheduleCode;
/* prettier-ignore-end */
