// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2p9VhVhxAWhB5Nusx9QUQ2
// Component: Te9KU2ZufSm0

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { Embed } from "@plasmicpkgs/plasmic-basic-components";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 2p9VhVhxAWhB5Nusx9QUQ2/projectcss
import sty from "./PlasmicMarianaTekBuyComponent.module.css"; // plasmic-import: Te9KU2ZufSm0/css

createPlasmicElementProxy;

export type PlasmicMarianaTekBuyComponent__VariantMembers = {};
export type PlasmicMarianaTekBuyComponent__VariantsArgs = {};
type VariantPropType = keyof PlasmicMarianaTekBuyComponent__VariantsArgs;
export const PlasmicMarianaTekBuyComponent__VariantProps =
  new Array<VariantPropType>();

export type PlasmicMarianaTekBuyComponent__ArgsType = {
  marianaTekBuySlot?: React.ReactNode;
};
type ArgPropType = keyof PlasmicMarianaTekBuyComponent__ArgsType;
export const PlasmicMarianaTekBuyComponent__ArgProps = new Array<ArgPropType>(
  "marianaTekBuySlot"
);

export type PlasmicMarianaTekBuyComponent__OverridesType = {
  marianaTek?: Flex__<"section">;
  embedHtml?: Flex__<typeof Embed>;
};

export interface DefaultMarianaTekBuyComponentProps {
  marianaTekBuySlot?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicMarianaTekBuyComponent__RenderFunc(props: {
  variants: PlasmicMarianaTekBuyComponent__VariantsArgs;
  args: PlasmicMarianaTekBuyComponent__ArgsType;
  overrides: PlasmicMarianaTekBuyComponent__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $translator = usePlasmicTranslator?.();

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <section
      data-plasmic-name={"marianaTek"}
      data-plasmic-override={overrides.marianaTek}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.marianaTek
      )}
    >
      {renderPlasmicSlot({
        defaultContents: null,
        value: args.marianaTekBuySlot
      })}
      <Embed
        data-plasmic-name={"embedHtml"}
        data-plasmic-override={overrides.embedHtml}
        className={classNames("__wab_instance", sty.embedHtml)}
        code={'<div data-mariana-integrations="/buy"></div>'}
      />
    </section>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  marianaTek: ["marianaTek", "embedHtml"],
  embedHtml: ["embedHtml"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  marianaTek: "section";
  embedHtml: typeof Embed;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMarianaTekBuyComponent__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMarianaTekBuyComponent__VariantsArgs;
    args?: PlasmicMarianaTekBuyComponent__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicMarianaTekBuyComponent__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMarianaTekBuyComponent__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMarianaTekBuyComponent__ArgProps,
          internalVariantPropNames: PlasmicMarianaTekBuyComponent__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMarianaTekBuyComponent__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "marianaTek") {
    func.displayName = "PlasmicMarianaTekBuyComponent";
  } else {
    func.displayName = `PlasmicMarianaTekBuyComponent.${nodeName}`;
  }
  return func;
}

export const PlasmicMarianaTekBuyComponent = Object.assign(
  // Top-level PlasmicMarianaTekBuyComponent renders the root element
  makeNodeComponent("marianaTek"),
  {
    // Helper components rendering sub-elements
    embedHtml: makeNodeComponent("embedHtml"),

    // Metadata about props expected for PlasmicMarianaTekBuyComponent
    internalVariantProps: PlasmicMarianaTekBuyComponent__VariantProps,
    internalArgProps: PlasmicMarianaTekBuyComponent__ArgProps
  }
);

export default PlasmicMarianaTekBuyComponent;
/* prettier-ignore-end */
