// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2p9VhVhxAWhB5Nusx9QUQ2
// Component: 8IV2OEDcUMSX

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { useScreenVariants as useScreenVariants_0QmF6MtAnaU } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: _0qmF6MTAnaU/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 2p9VhVhxAWhB5Nusx9QUQ2/projectcss
import sty from "./PlasmicPrivacyPolicyContainer.module.css"; // plasmic-import: 8IV2OEDcUMSX/css

createPlasmicElementProxy;

export type PlasmicPrivacyPolicyContainer__VariantMembers = {};
export type PlasmicPrivacyPolicyContainer__VariantsArgs = {};
type VariantPropType = keyof PlasmicPrivacyPolicyContainer__VariantsArgs;
export const PlasmicPrivacyPolicyContainer__VariantProps =
  new Array<VariantPropType>();

export type PlasmicPrivacyPolicyContainer__ArgsType = {};
type ArgPropType = keyof PlasmicPrivacyPolicyContainer__ArgsType;
export const PlasmicPrivacyPolicyContainer__ArgProps = new Array<ArgPropType>();

export type PlasmicPrivacyPolicyContainer__OverridesType = {
  container3?: Flex__<"div">;
};

export interface DefaultPrivacyPolicyContainerProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPrivacyPolicyContainer__RenderFunc(props: {
  variants: PlasmicPrivacyPolicyContainer__VariantsArgs;
  args: PlasmicPrivacyPolicyContainer__ArgsType;
  overrides: PlasmicPrivacyPolicyContainer__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $translator = usePlasmicTranslator?.();

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_0QmF6MtAnaU()
  });

  return (
    <div
      data-plasmic-name={"container3"}
      data-plasmic-override={overrides.container3}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.container3
      )}
    >
      <Stack__
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__boFi5)}
      >
        <h4
          className={classNames(
            projectcss.all,
            projectcss.h4,
            projectcss.__wab_text,
            sty.h4__ufiiu
          )}
        >
          <Trans__>
            {hasVariant(globalVariants, "screen", "mobile")
              ? "Privacy Policy"
              : "Privacy Policy"}
          </Trans__>
        </h4>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__zspXt
          )}
        >
          <Trans__>
            {
              'Welcome to Halcyon Studio\'s Privacy Policy. This document outlines how we collect, use, disclose, and protect your personal information when you interact with our website and related services. By accessing or using our website located at www.halcyonstudio.com, or any other websites, pages, features, mobile applications, or technology owned or operated by Halcyon Studio (referred to as "Halcyon Studio," "the Company," "we," "us," or "our"), you agree to the practices described in this Privacy Policy.'
            }
          </Trans__>
        </div>
      </Stack__>
      <Stack__
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__kzY0)}
      >
        <h4
          className={classNames(
            projectcss.all,
            projectcss.h4,
            projectcss.__wab_text,
            sty.h4__uC3Bh
          )}
        >
          <Trans__>
            {hasVariant(globalVariants, "screen", "mobile")
              ? "Information We Collect"
              : "Information We Collect"}
          </Trans__>
        </h4>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__wr4Yb
          )}
        >
          <Trans__>
            {
              "We collect information that you voluntarily provide to us when you interact with our services. This may include:\n\nPersonal information such as your name, email address, phone number, and billing information when you register for an account or make a purchase.\nInformation you provide when you contact us for customer support or participate in surveys or promotions.\nUsage data and technical information automatically collected when you access our website, such as your IP address, browser type, device information, and cookies."
            }
          </Trans__>
        </div>
      </Stack__>
      <Stack__
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__xS8Ks)}
      >
        <h4
          className={classNames(
            projectcss.all,
            projectcss.h4,
            projectcss.__wab_text,
            sty.h4___6ZefJ
          )}
        >
          <Trans__>
            {hasVariant(globalVariants, "screen", "mobile")
              ? "How We Use Your Information"
              : "How We Use Your Information"}
          </Trans__>
        </h4>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__hgqAz
          )}
        >
          <Trans__>
            {
              "We use the information we collect for various purposes, including:\n\nProviding and improving our services, including customizing content and features.\nCommunicating with you, such as responding to your inquiries and sending you updates and notifications.\nProcessing transactions and fulfilling orders.\nAnalyzing trends and user interactions to optimize our website and services.\nProtecting our rights, property, and safety, as well as that of our users and the public."
            }
          </Trans__>
        </div>
      </Stack__>
      <Stack__
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__llwNp)}
      >
        <h4
          className={classNames(
            projectcss.all,
            projectcss.h4,
            projectcss.__wab_text,
            sty.h4__lJqqj
          )}
        >
          <Trans__>
            {hasVariant(globalVariants, "screen", "mobile")
              ? "Information Sharing and Disclosure"
              : "Information Sharing and Disclosure"}
          </Trans__>
        </h4>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__xtLpa
          )}
        >
          <Trans__>
            {
              "We may share your personal information with third-party service providers who assist us in operating our website and providing services to you. These service providers are contractually obligated to use your information only for the purposes of providing services to us and are required to maintain the confidentiality and security of your information.\n\nWe may also disclose your information in response to legal requests or to comply with applicable laws and regulations, enforce our policies, or protect our rights, property, or safety."
            }
          </Trans__>
        </div>
      </Stack__>
      <Stack__
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__tYwy1)}
      >
        <h4
          className={classNames(
            projectcss.all,
            projectcss.h4,
            projectcss.__wab_text,
            sty.h4__gN6S
          )}
        >
          <Trans__>
            {hasVariant(globalVariants, "screen", "mobile")
              ? "Your Choices"
              : "Your Choices"}
          </Trans__>
        </h4>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__g07F2
          )}
        >
          <Trans__>
            {
              "You have the following choices regarding your personal information:\n\nYou can access, update, or delete your personal information by logging into your account settings or contacting us directly.\nYou can opt-out of receiving promotional communications from us by following the instructions provided in such communications.\nYou can adjust your browser settings to refuse cookies or alert you when cookies are being sent. However, please note that some features of our website may not function properly if cookies are disabled."
            }
          </Trans__>
        </div>
      </Stack__>
      <Stack__
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__hc5Uk)}
      >
        <h4
          className={classNames(
            projectcss.all,
            projectcss.h4,
            projectcss.__wab_text,
            sty.h4__uwAtf
          )}
        >
          <Trans__>
            {hasVariant(globalVariants, "screen", "mobile")
              ? "Data Security"
              : "Data Security"}
          </Trans__>
        </h4>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__cY88G
          )}
        >
          <Trans__>
            {
              "We take reasonable measures to protect the security of your personal information and prevent unauthorized access, disclosure, alteration, or destruction. However, no method of transmission over the internet or electronic storage is 100% secure, and we cannot guarantee absolute security."
            }
          </Trans__>
        </div>
      </Stack__>
      <Stack__
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__top1Q)}
      >
        <h4
          className={classNames(
            projectcss.all,
            projectcss.h4,
            projectcss.__wab_text,
            sty.h4__yOz1N
          )}
        >
          <Trans__>
            {hasVariant(globalVariants, "screen", "mobile")
              ? "Children's Privacy"
              : "Children's Privacy"}
          </Trans__>
        </h4>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__ywXQc
          )}
        >
          <Trans__>
            {
              "We may update this Cookie Policy from time to time. Any material changes will be reflected in the updated policy with an effective date. We encourage you to review this policy periodically for updates.\n\nThank you for reading our Cookie Policy."
            }
          </Trans__>
        </div>
      </Stack__>
      <Stack__
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__m4V1N)}
      >
        <h4
          className={classNames(
            projectcss.all,
            projectcss.h4,
            projectcss.__wab_text,
            sty.h4__cjgbm
          )}
        >
          <Trans__>
            {hasVariant(globalVariants, "screen", "mobile")
              ? "Changes to Our Privacy Policy"
              : "Changes to Our Privacy Policy"}
          </Trans__>
        </h4>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__kyiqq
          )}
        >
          <Trans__>
            {
              "We may update this Privacy Policy from time to time. Any material changes will be reflected in the updated policy with an effective date. We encourage you to review this policy periodically for updates."
            }
          </Trans__>
        </div>
      </Stack__>
      <Stack__
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__l9Yyp)}
      >
        <h4
          className={classNames(
            projectcss.all,
            projectcss.h4,
            projectcss.__wab_text,
            sty.h4___190NP
          )}
        >
          <Trans__>
            {hasVariant(globalVariants, "screen", "mobile")
              ? "Questions & Contact Information"
              : "Questions & Contact Information"}
          </Trans__>
        </h4>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___0N64H
          )}
        >
          <Trans__>
            {
              "If you have any questions or concerns regarding our Privacy Policy, please contact us at admin@halcyonstudio.us\n\nThank you for reading our Privacy Policy."
            }
          </Trans__>
        </div>
      </Stack__>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  container3: ["container3"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  container3: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPrivacyPolicyContainer__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPrivacyPolicyContainer__VariantsArgs;
    args?: PlasmicPrivacyPolicyContainer__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPrivacyPolicyContainer__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicPrivacyPolicyContainer__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPrivacyPolicyContainer__ArgProps,
          internalVariantPropNames: PlasmicPrivacyPolicyContainer__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPrivacyPolicyContainer__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "container3") {
    func.displayName = "PlasmicPrivacyPolicyContainer";
  } else {
    func.displayName = `PlasmicPrivacyPolicyContainer.${nodeName}`;
  }
  return func;
}

export const PlasmicPrivacyPolicyContainer = Object.assign(
  // Top-level PlasmicPrivacyPolicyContainer renders the root element
  makeNodeComponent("container3"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicPrivacyPolicyContainer
    internalVariantProps: PlasmicPrivacyPolicyContainer__VariantProps,
    internalArgProps: PlasmicPrivacyPolicyContainer__ArgProps
  }
);

export default PlasmicPrivacyPolicyContainer;
/* prettier-ignore-end */
